import { formatEventDate } from "../lib/eventSlate";

const pct = (value) => value == null ? "—" : `${(Number(value) * 100).toFixed(1)}%`;

export default function FootballIntel({ sport, rows = [] }) {
  if (sport !== "nfl" && sport !== "cfb") return null;
  return <section className="fbintel" aria-label={`${sport.toUpperCase()} game intel`}>
    <div className="fbintel__head"><div><span>{sport.toUpperCase()} · GAME INTEL · WHAT CHANGES THE BET</span><h2>Market &amp; Intel</h2></div><small>Unknown stays unknown</small></div>
    {rows.length === 0 ? <div className="fbintel__empty">Intel appears with the selected event-day slate.</div>
      : <div className="fbintel__grid">{rows.slice(0, 6).map((row) => <article className="fbintel__card" key={row.gameId}>
          <div className="fbintel__match"><b>{row.matchup}</b><span>{formatEventDate(row.commenceTime ? new Date(row.commenceTime).toLocaleDateString("en-CA", { timeZone: "America/New_York" }) : null, { compact: true })}</span></div>
          {row.marketOnly ? <div className="fbintel__marketonly"><b>MARKET VIEW ONLY</b><span>No independent WizePicks model edge is claimed for this matchup.</span></div>
            : row.modelSignal ? <div className="fbintel__signal"><span>SHARP EDGE · MODEL VS MARKET</span><b>{row.modelSignal.pick}</b><small>{row.modelSignal.market} · {pct(row.modelSignal.probability)} · {Number(row.modelSignal.edge) >= 0 ? "+" : ""}{Number(row.modelSignal.edge).toFixed(1)}% edge</small></div>
            : <div className="fbintel__marketonly"><b>NO QUALIFYING MODEL SIGNAL</b><span>Market information remains available without inventing an edge.</span></div>}
          <dl><div><dt>Market pulse</dt><dd>{row.marketLean || "No clear verified consensus"}</dd></div><div><dt>Line move</dt><dd>{row.lineMovement || "No verified movement yet"}</dd></div><div><dt>Matchup edge</dt><dd>{row.matchupEdge || "No independent rated matchup signal"}</dd></div><div><dt>Recent form</dt><dd>{row.recentForm || "No verified recent-form input"}</dd></div><div><dt>Venue</dt><dd>{row.venue}</dd></div><div><dt>Weather</dt><dd>{row.weather || "No verified weather input"}</dd></div><div><dt>Availability</dt><dd>{row.availability || "No verified player-status update"}</dd></div></dl>
        </article>)}</div>}
  </section>;
}

export const FOOTBALL_INTEL_CSS = `
.fbintel{box-sizing:border-box;min-width:0;margin:14px 0;border:1px solid #273139;border-radius:14px;background:linear-gradient(180deg,#11171b,#0b1013);overflow:hidden;color:#e8ecef}.fbintel *{box-sizing:border-box}.fbintel__head{display:flex;align-items:flex-end;justify-content:space-between;gap:12px;padding:13px 14px;border-bottom:1px solid #242d33}.fbintel__head span{display:block;font:700 8px "IBM Plex Mono",monospace;letter-spacing:1.1px;color:#C9A86A}.fbintel__head h2{margin:3px 0 0;font:800 21px "Barlow Condensed",sans-serif}.fbintel__head small{font:600 8px "IBM Plex Mono",monospace;color:#66737c}.fbintel__grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:1px;background:#20282e}.fbintel__card{min-width:0;background:#0d1215;padding:13px}.fbintel__match{display:flex;justify-content:space-between;align-items:flex-start;gap:9px}.fbintel__match b{min-width:0;font:800 16px/1.15 "Barlow Condensed",sans-serif;overflow-wrap:anywhere}.fbintel__match span{flex:0 0 auto;font:600 8px "IBM Plex Mono",monospace;color:#71808a}.fbintel__signal,.fbintel__marketonly{margin-top:11px;border:1px solid rgba(201,168,106,.25);border-radius:9px;background:rgba(201,168,106,.06);padding:9px 10px}.fbintel__signal span,.fbintel__marketonly b{display:block;font:700 8px "IBM Plex Mono",monospace;letter-spacing:.8px;color:#C9A86A}.fbintel__signal b{display:block;margin-top:3px;font:800 18px "Barlow Condensed",sans-serif;overflow-wrap:anywhere}.fbintel__signal small,.fbintel__marketonly span{display:block;margin-top:3px;font:500 9px/1.45 "IBM Plex Mono",monospace;color:#8d99a2}.fbintel__card dl{margin:10px 0 0}.fbintel__card dl div{display:grid;grid-template-columns:84px minmax(0,1fr);gap:8px;padding:5px 0;border-top:1px solid #1b2328}.fbintel__card dt{font:700 8px "IBM Plex Mono",monospace;color:#65727b;text-transform:uppercase}.fbintel__card dd{margin:0;font:500 9.5px/1.35 "IBM Plex Mono",monospace;color:#afb8be;overflow-wrap:anywhere}.fbintel__empty{padding:25px 14px;text-align:center;color:#75828b;font-size:12px}@media(max-width:620px){.fbintel__grid{grid-template-columns:1fr}.fbintel__card{padding:12px}.fbintel__head{align-items:flex-start}.fbintel__head small{padding-top:3px}.fbintel__card dl div{grid-template-columns:76px minmax(0,1fr)}}`;
