begin;

create table public.football_weekly_context_snapshots (
  id bigint generated by default as identity primary key,
  league text not null,
  event_id text not null,
  espn_game_id text,
  game_date date not null,
  kickoff_at timestamptz not null,
  captured_at timestamptz not null,
  home_team_id text,
  away_team_id text,
  home_team text not null,
  away_team text not null,
  prediction_keys jsonb not null,
  context_status text not null,
  context_confidence text not null,
  context_completeness double precision not null,
  structured_context jsonb not null,
  material_items jsonb not null,
  unresolved_items jsonb not null,
  source_context jsonb not null,
  context_version text not null,
  input_fingerprint text not null,
  created_at timestamptz not null default now(),

  constraint football_weekly_context_league_ck
    check (league in ('nfl', 'cfb')),
  constraint football_weekly_context_before_kickoff_ck
    check (captured_at < kickoff_at),
  constraint football_weekly_context_status_ck
    check (context_status in ('CLEAR', 'MATERIAL CONTEXT', 'UNRESOLVED MATERIAL CONTEXT')),
  constraint football_weekly_context_confidence_ck
    check (context_confidence in ('low', 'medium', 'high')),
  constraint football_weekly_context_completeness_ck
    check (context_completeness >= 0 and context_completeness <= 1),
  constraint football_weekly_context_json_shapes_ck
    check (
      jsonb_typeof(prediction_keys) = 'array'
      and jsonb_typeof(structured_context) = 'object'
      and jsonb_typeof(material_items) = 'array'
      and jsonb_typeof(unresolved_items) = 'array'
      and jsonb_typeof(source_context) = 'object'
    ),
  constraint football_weekly_context_status_evidence_ck
    check (
      (context_status = 'CLEAR'
        and jsonb_array_length(material_items) = 0
        and jsonb_array_length(unresolved_items) = 0)
      or (context_status = 'MATERIAL CONTEXT'
        and jsonb_array_length(material_items) > 0
        and jsonb_array_length(unresolved_items) = 0)
      or (context_status = 'UNRESOLVED MATERIAL CONTEXT'
        and jsonb_array_length(unresolved_items) > 0)
    ),
  constraint football_weekly_context_version_ck
    check (context_version ~ '^football-weekly-context-v[0-9]+-[0-9]{4}-[0-9]{2}-[0-9]{2}$'),
  constraint football_weekly_context_fingerprint_ck
    check (input_fingerprint ~ '^[0-9a-f]{64}$'),
  constraint football_weekly_context_snapshot_uk
    unique (league, event_id, captured_at, context_version)
);

create index football_weekly_context_game_idx
  on public.football_weekly_context_snapshots (league, game_date, event_id);

alter table public.football_weekly_context_snapshots enable row level security;

revoke all on table public.football_weekly_context_snapshots from public, anon, authenticated, service_role;
grant select, insert on table public.football_weekly_context_snapshots to service_role;

revoke all on sequence public.football_weekly_context_snapshots_id_seq from public, anon, authenticated, service_role;
grant usage, select on sequence public.football_weekly_context_snapshots_id_seq to service_role;

create function public.prevent_football_weekly_context_mutation()
returns trigger
language plpgsql
set search_path = public, pg_temp
as $$
begin
  raise exception 'football weekly context snapshots are immutable';
end;
$$;

revoke all on function public.prevent_football_weekly_context_mutation() from public, anon, authenticated;
grant execute on function public.prevent_football_weekly_context_mutation() to service_role;

create trigger football_weekly_context_immutable
before update or delete on public.football_weekly_context_snapshots
for each row execute function public.prevent_football_weekly_context_mutation();

commit;
