export const SEO_PHASE2_PAGES = Object.freeze({
  nflMatchup: Object.freeze({
    kind: "matchup",
    sport: "nfl",
    path: "/nfl/new-england-patriots-vs-seattle-seahawks-prediction-odds-2026-09-09",
    title: "New England Patriots vs. Seattle Seahawks Prediction & Odds – September 9, 2026 | WizePicks",
    description: "New England Patriots vs. Seattle Seahawks prediction, kickoff time, sportsbook context, and public-safe WizePicks analysis for September 9, 2026.",
    h1: "New England Patriots vs. Seattle Seahawks Prediction & Odds",
    away: "New England Patriots",
    home: "Seattle Seahawks",
    date: "2026-09-09",
    startDate: "2026-09-10T00:20:00Z",
    hub: "/nfl-picks",
    hubLabel: "NFL picks",
  }),
  cfbMatchup: Object.freeze({
    kind: "matchup",
    sport: "cfb",
    path: "/college-football/missouri-tigers-vs-kansas-jayhawks-prediction-odds-2026-09-11",
    title: "Missouri Tigers vs. Kansas Jayhawks Prediction & Odds – September 11, 2026 | WizePicks",
    description: "Missouri Tigers vs. Kansas Jayhawks prediction, kickoff time, market context, and public-safe WizePicks analysis for September 11, 2026.",
    h1: "Missouri Tigers vs. Kansas Jayhawks Prediction & Odds",
    away: "Missouri Tigers",
    home: "Kansas Jayhawks",
    date: "2026-09-11",
    startDate: "2026-09-12T00:00:00Z",
    hub: "/college-football-picks",
    hubLabel: "College football picks",
  }),
  mlbMatchup: Object.freeze({
    kind: "matchup",
    sport: "mlb",
    path: "/mlb/cleveland-guardians-vs-baltimore-orioles-prediction-odds-2026-09-08",
    title: "Cleveland Guardians vs. Baltimore Orioles Prediction & Odds – September 8, 2026 | WizePicks",
    description: "Cleveland Guardians vs. Baltimore Orioles prediction, first-pitch time, sportsbook context, and public-safe WizePicks analysis for September 8, 2026.",
    h1: "Cleveland Guardians vs. Baltimore Orioles Prediction & Odds",
    away: "Cleveland Guardians",
    home: "Baltimore Orioles",
    date: "2026-09-08",
    startDate: "2026-09-08T18:35:00-04:00",
    hub: "/mlb-picks",
    hubLabel: "MLB picks",
  }),
  nflWeek: Object.freeze({
    kind: "slate",
    sport: "nfl",
    path: "/nfl-picks/week-1-2026",
    title: "NFL Week 1 Picks & Predictions 2026 | WizePicks",
    description: "NFL Week 1 picks and predictions for 2026 with the current schedule, kickoff times, sportsbook context, and public-safe WizePicks analysis.",
    h1: "NFL Week 1 Picks & Predictions",
    label: "2026 · WEEK 1",
    hub: "/nfl-picks",
    hubLabel: "NFL picks this week",
  }),
  cfbWeek: Object.freeze({
    kind: "slate",
    sport: "cfb",
    path: "/college-football-picks/week-2-2026",
    title: "College Football Week 2 Picks & Predictions 2026 | WizePicks",
    description: "College football Week 2 picks and predictions for 2026 with current matchups, kickoff times, rated-versus-market context, and public-safe WizePicks analysis.",
    h1: "College Football Week 2 Picks & Predictions",
    label: "2026 · WEEK 2",
    hub: "/college-football-picks",
    hubLabel: "College football picks today",
  }),
  mlbDay: Object.freeze({
    kind: "slate",
    sport: "mlb",
    path: "/mlb-picks/2026-09-08",
    title: "MLB Picks for September 8, 2026 | WizePicks",
    description: "MLB picks and predictions for September 8, 2026 with the day’s matchups, first-pitch times, sportsbook context, and public-safe WizePicks analysis.",
    h1: "MLB Picks for September 8, 2026",
    label: "TUESDAY · SEPTEMBER 8, 2026",
    date: "2026-09-08",
    hub: "/mlb-picks",
    hubLabel: "MLB picks today",
  }),
  mlbPerformance: Object.freeze({
    kind: "performance",
    sport: "mlb",
    league: "mlb",
    path: "/performance/mlb",
    title: "MLB Prediction Performance & Model Record | WizePicks",
    description: "The authoritative graded WizePicks MLB prediction record, including wins, losses, units, ROI methodology, and market-level performance.",
    h1: "MLB Prediction Performance",
    hub: "/mlb-picks",
    hubLabel: "MLB picks",
  }),
  nflPerformance: Object.freeze({
    kind: "performance",
    sport: "nfl",
    league: "nfl",
    path: "/performance/nfl",
    title: "NFL Prediction Performance & Model Record | WizePicks",
    description: "The authoritative graded WizePicks NFL prediction record, including wins, losses, units, ROI, and market-level performance.",
    h1: "NFL Prediction Performance",
    hub: "/nfl-picks",
    hubLabel: "NFL picks",
  }),
  cfbPerformance: Object.freeze({
    kind: "performance",
    sport: "cfb",
    league: "cfb",
    path: "/performance/college-football",
    title: "College Football Prediction Performance & Model Record | WizePicks",
    description: "The authoritative graded WizePicks college-football prediction record, including wins, losses, units, ROI, and market-level performance.",
    h1: "College Football Prediction Performance",
    hub: "/college-football-picks",
    hubLabel: "College football picks",
  }),
});

export const SEO_PHASE2_LIST = Object.freeze(Object.values(SEO_PHASE2_PAGES));

export const SEO_PHASE2_BY_PATH = Object.freeze(
  Object.fromEntries(SEO_PHASE2_LIST.map((page) => [page.path, page])),
);

export function seoPhase2ForSport(sport) {
  return SEO_PHASE2_LIST.filter((page) => page.sport === sport);
}
